/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectionCell: typeof import('./components/ConnectionCell.vue')['default']
    DelayBadge: typeof import('./components/DelayBadge.vue')['default']
    ElAlert: typeof import('element-plus/es/components/alert/index')['ElAlert']
    ElButton: typeof import('element-plus/es/components/button/index')['ElButton']
    ElCheckbox: typeof import('element-plus/es/components/checkbox/index')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es/components/config-provider/index')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es/components/descriptions/index')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es/components/descriptions/index')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es/components/dialog/index')['ElDialog']
    ElDrawer: typeof import('element-plus/es/components/drawer/index')['ElDrawer']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es/components/form/index')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index')['ElFormItem']
    ElIcon: typeof import('element-plus/es/components/icon/index')['ElIcon']
    ElInput: typeof import('element-plus/es/components/input/index')['ElInput']
    ElOption: typeof import('element-plus/es/components/select/index')['ElOption']
    ElProgress: typeof import('element-plus/es/components/progress/index')['ElProgress']
    ElRadioButton: typeof import('element-plus/es/components/radio/index')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es/components/radio/index')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es/components/select/index')['ElSelect']
    ElSwitch: typeof import('element-plus/es/components/switch/index')['ElSwitch']
    ElTableV2: typeof import('element-plus/es/components/table-v2/index')['ElTableV2']
    ElTag: typeof import('element-plus/es/components/tag/index')['ElTag']
    ElTooltip: typeof import('element-plus/es/components/tooltip/index')['ElTooltip']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorState: typeof import('./components/ErrorState.vue')['default']
    LineChartSvg: typeof import('./components/charts/LineChartSvg.vue')['default']
    MemoryChart: typeof import('./components/charts/MemoryChart.vue')['default']
    ModeSwitcher: typeof import('./components/ModeSwitcher.vue')['default']
    NodeIcon: typeof import('./components/NodeIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecretPrompt: typeof import('./components/SecretPrompt.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
    StatusPill: typeof import('./components/StatusPill.vue')['default']
    TrafficChart: typeof import('./components/charts/TrafficChart.vue')['default']
    YamlEditor: typeof import('./components/YamlEditor.vue')['default']
  }
}
